# Generated by Django 5.1.6 on 2025-02-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider1',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='image2/'),
        ),
        migrations.AddField(
            model_name='slider1',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slider2',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='image2/'),
        ),
        migrations.AddField(
            model_name='slider2',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slider3',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='image2/'),
        ),
        migrations.AddField(
            model_name='slider3',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
