# Generated by Django 5.1.6 on 2025-12-08 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('accounts', '0001_initial'),
        ('hostel', '0001_initial'),
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=50, unique=True)),
                ('admission_date', models.DateField()),
                ('roll_number', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('caste', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(default='Pakistani', max_length=50)),
                ('father_name', models.CharField(max_length=200)),
                ('father_phone', models.CharField(max_length=20)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('father_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mother_name', models.CharField(max_length=200)),
                ('mother_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('guardian_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emergency_contact_name', models.CharField(max_length=200)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('emergency_contact_relation', models.CharField(max_length=50)),
                ('previous_school', models.CharField(blank=True, max_length=200, null=True)),
                ('previous_class', models.CharField(blank=True, max_length=50, null=True)),
                ('medical_conditions', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('GRADUATED', 'Graduated'), ('TRANSFERRED', 'Transferred'), ('EXPELLED', 'Expelled')], default='ACTIVE', max_length=20)),
                ('uses_transport', models.BooleanField(default=False)),
                ('is_hosteler', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.campus')),
                ('current_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_students', to='academics.class')),
                ('hostel_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='hostel.room')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='transport.route')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
                'ordering': ['admission_number'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('BIRTH_CERTIFICATE', 'Birth Certificate'), ('TRANSFER_CERTIFICATE', 'Transfer Certificate'), ('MARKSHEET', 'Marksheet'), ('ID_PROOF', 'ID Proof'), ('PHOTO', 'Photo'), ('OTHER', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='student_documents/')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_student_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Document',
                'verbose_name_plural': 'Student Documents',
                'db_table': 'student_documents',
            },
        ),
        migrations.CreateModel(
            name='StudentHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='in cm', max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='in kg', max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('next_checkup_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_health_records', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Health Record',
                'verbose_name_plural': 'Student Health Records',
                'db_table': 'student_health_records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudentPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='accounts.academicyear')),
                ('from_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoted_from', to='academics.class')),
                ('from_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promoted_from_section', to='academics.section')),
                ('promoted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_promotions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='students.student')),
                ('to_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoted_to', to='academics.class')),
                ('to_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promoted_to_section', to='academics.section')),
            ],
            options={
                'verbose_name': 'Student Promotion',
                'verbose_name_plural': 'Student Promotions',
                'db_table': 'student_promotions',
                'ordering': ['-promotion_date'],
            },
        ),
        migrations.CreateModel(
            name='Sibling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('BROTHER', 'Brother'), ('SISTER', 'Sister'), ('TWIN', 'Twin')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siblings_as_student1', to='students.student')),
                ('student2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siblings_as_student2', to='students.student')),
            ],
            options={
                'verbose_name': 'Sibling',
                'verbose_name_plural': 'Siblings',
                'db_table': 'siblings',
                'unique_together': {('student1', 'student2')},
            },
        ),
    ]
