# Generated by Django 5.1.6 on 2025-02-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepage',
            name='compulsory_subject',
        ),
        migrations.RemoveField(
            model_name='coursepage',
            name='elactive_subject',
        ),
        migrations.AddField(
            model_name='coursepage',
            name='compulsory_subjects',
            field=models.ManyToManyField(blank=True, null=True, related_name='course_compulsory_subjects', to='courses.compulsorysubjects'),
        ),
        migrations.AddField(
            model_name='coursepage',
            name='elective_subjects',
            field=models.ManyToManyField(blank=True, null=True, related_name='course_elective_subjects', to='courses.elactivesubjects'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
