# Generated by Django 5.1.6 on 2025-02-15 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_coursepage_compulsory_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursepage',
            old_name='title',
            new_name='course_name',
        ),
    ]
