# Generated by Django 5.1.6 on 2025-02-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_title_coursepage_course_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursepage',
            old_name='content',
            new_name='course_detail',
        ),
        migrations.AddField(
            model_name='coursepage',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
