# Generated by Django 5.1.6 on 2025-02-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('icon_class', models.CharField(choices=[('fa-facebook', 'Facebook'), ('fa-twitter', 'Twitter'), ('fa-linkedin', 'LinkedIn'), ('fa-instagram', 'Instagram')], max_length=50)),
            ],
        ),
    ]
