# Generated by Django 5.1.6 on 2025-02-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='icon_class',
            field=models.CharField(choices=[('fa-facebook', 'Facebook'), ('fa-twitter', 'Twitter'), ('fa-linkedin', 'LinkedIn'), ('fa-instagram', 'Instagram'), ('fa-youtube', 'YouTube')], max_length=50),
        ),
    ]
