# Generated by Django 5.1.6 on 2025-02-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='image',
            field=models.ImageField(default='', upload_to='about'),
            preserve_default=False,
        ),
    ]
