# Generated by Django 5.1.6 on 2025-02-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headers', '0002_weeklyschooltiming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyschooltiming',
            name='day',
            field=models.CharField(max_length=50),
        ),
    ]
