# Generated by Django 5.1.6 on 2025-12-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headers', '0003_alter_weeklyschooltiming_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='icon_class',
            field=models.CharField(choices=[('fa-facebook', 'Facebook'), ('fa-twitter', 'Twitter'), ('fa-linkedin', 'LinkedIn'), ('fa-instagram', 'Instagram'), ('fa-youtube', 'YouTube'), ('fa-whatsapp', 'Whatsapp')], max_length=50),
        ),
    ]
